# Generated by Django 5.2.5 on 2025-08-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_replace_license_key_category'),
        ('store', '0004_email_access_link'),
    ]

    operations = [
    ]
