# Generated by Django 5.2.5 on 2025-08-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_gamekey'),
        ('store', '0005_merge_20250824_0106'),
    ]

    operations = [
    ]
