# Generated by Django 5.2.5 on 2025-08-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_chatmessage'),
        ('store', '0006_merge_0003_delete_gamekey_0005_merge_20250824_0106'),
    ]

    operations = [
    ]
