# Generated by Django 5.2.5 on 2025-08-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20250824_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('offline-account', 'Offline Account'), ('online-account', 'Online Account'), ('account-rent', 'Account Rent')], max_length=50),
        ),
    ]
