# Generated by Django 5.2.5 on 2025-08-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_chatmessage_is_read'),
        ('store', '0008_alter_game_category'),
    ]

    operations = [
    ]
