# Generated by Django 5.2.5 on 2025-08-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_20250824_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChat',
            fields=[
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
    ]
