# Generated by Django 5.2.5 on 2025-08-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_chatmessage_image'),
        ('store', '0010_orderchat'),
    ]

    operations = [
    ]
